service: serverless-processing

frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

custom:
  tableName: process-configs


provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  create-queue:
    handler: bin/create-queue
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          maximumRetryAttempts: 2
          enabled: true
          arn:
            Fn::GetAtt:
              - ProcessConfigTable
              - StreamArn
    environment:
      DYNAMO_JOB_CONFIGS_TABLE_NAME: ${self:custom.tableName}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:scan
          - dynamodb:ListStreams
          - dynamodb:DescribeTable
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.tableName}
      - Effect: Allow
        Action:
          - sqs:TagQueue
          - sqs:CreateQueue
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
        Resource: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:*

resources:
  Resources:
    ProcessConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    LambdaCodeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: kinluek-serverless-processing-code
