service: serverless-processing

frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

custom:
  tableName: task-sets


provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-2

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  initiate-task-queues:
    handler: bin/initiate-task-queues
    environment:
      DYNAMO_TASK_TABLE_NAME: ${self:custom.tableName}
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:scan
        Resource: arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.tableName}
      - Effect: Allow
        Action:
          - sqs:TagQueue
          - sqs:CreateQueue
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
        Resource: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:*

resources:
  Resources:
    TaskSetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: name_id
            AttributeType: S
        KeySchema:
          - AttributeName: name_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    LambdaCodeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: kinluek-serverless-processing-code
